services:
  backend:
    build: 
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    develop:
      build: backend/.
      watch:
        - action: rebuild
          path: backend/.
  frontend:
    build: frontend/.
    ports:
      - '5173:80'
    develop:
      build: 
        context: frontend/.
        dockerfile: Dockerfile.dev
      watch:
        - action: rebuild
          path: frontend/.
